# Generated by Django 5.2.4 on 2025-08-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
