name: Security Scan

on:
  push:
  pull_request:
  schedule:
    - cron: "0 2 * * 0"

jobs:
  code-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Bandit (SAST)
        run: |
          pip install bandit
          bandit -r . -ll

      - name: pip-audit (deps vulns)
        run: |
          pip install pip-audit
          pip-audit

  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source=. --no-git -v
