name: Security Scan

on:
  push:
  pull_request:
  schedule:
    - cron: "0 2 * * 0"  # Every Sunday at 2 AM UTC

permissions:
  contents: read
  security-events: write

jobs:
  code-security:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Install tools
        run: |
          pip install bandit pip-audit
          
      - name: Run Bandit (Python SAST)
        run: bandit -r . -ll --skip B101
        
      - name: Run pip-audit (Dependency Vulnerabilities)
        run: pip-audit

  secrets:
    name: Secret Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch full history for better gitleaks scanning
          fetch-depth: 0
          
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Optional: Add dependency scanning
  dependency-scan:
    name: Dependency Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'