name: Security Scan

on:
  push:
  pull_request:
  schedule:
    - cron: "0 2 * * 0"  # Every Sunday at 2 AM UTC

jobs:
  code-security:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install tools
        run: |
          pip install bandit pip-audit

      - name: Run Bandit (Python SAST)
        run: bandit -r . -ll --skip B101

      - name: Run pip-audit (Dependency Vulnerabilities)
        run: pip-audit

  secrets:
    name: Secret Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source=. --no-git -v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
